GRANT SELECT ON TFS_PRES.ORC_IRS_DETAY TO TFS_YKY;

GRANT SELECT ON TFS_PRES.ORC_IRS_MASTER TO TFS_YKY;

GRANT SELECT ON TFS_PRES.SIS_SKU_DEF TO TFS_YKY;

GRANT SELECT ON TFS_FIRMA.SAP_CONVERSION TO TFS_YKY;

GRANT SELECT ON TFS_SUP.V_SUP_TOFAS_RESPS TO TFS_YKY;
